//
// SimpleEmail.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SimpleEmail: JSONEncodable {
    public var triggerTag: String?
    public var sender: String?
    public var subject: String?
    public var personal: String?
    public var body: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["triggerTag"] = self.triggerTag
        nillableDictionary["sender"] = self.sender
        nillableDictionary["subject"] = self.subject
        nillableDictionary["personal"] = self.personal
        nillableDictionary["body"] = self.body
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
